# x64 architecture:
FROM openjdk:8-jre-slim
# arm32 architecture:
#FROM arm32v7/openjdk:8-jre-slim

RUN apt update && apt upgrade -y && apt install -y wget

WORKDIR /opt

ENV version 0.9.1

RUN wget https://github.com/AaltoAsia/O-MI/releases/download/${version}/o-mi-node-${version}.tgz
RUN tar xfz o-mi-node-${version}.tgz && rm o-mi-node-${version}.tgz

COPY ./components/o-mi-node/o-mi-node-configuration/application.conf /opt/o-mi-node-${version}/configs/

VOLUME /data

# HTTP endpoint
EXPOSE 8080
# admin console:
EXPOSE 8180

WORKDIR /opt/o-mi-node-${version}

RUN echo "rm -rf /data/*" > purge-data-and-run.sh
RUN echo "bin/o-mi-node" >> purge-data-and-run.sh
RUN chmod +x purge-data-and-run.sh

CMD ./purge-data-and-run.sh
