# FROM arm32v7/node:6.11.5-slim
FROM node:latest

WORKDIR /app

ADD ./components/web-app/public ./public/
ADD ./components/web-app/function-lib.js ./
ADD ./components/web-app/index.html ./
ADD ./components/web-app/package.json ./
ADD ./components/web-app/main.js ./

RUN npm install

CMD node main.js
