# amd64 architecture:
FROM debian:stretch-slim
# armhf architecture:
#FROM arm32v7/debian:stretch-slim

RUN apt update && apt upgrade -y && apt install -y curl

WORKDIR /opt/o-mi-node-bootstrap
COPY ./components/o-mi-node/o-mi-node-bootstrap/*.xml ./
COPY ./components/o-mi-node/o-mi-node-bootstrap/*.sh  ./
